### ISSUE TITLE
missing result

### ISSUE THREAD

**Issue by Translator5** [scherebedov/interslavic#61]
BTW: KUDOS for this project! && wuld be nice if it would be possible to print the whole slovnik as pdf with all variants of writing - for having a offline words database.

Searching from Russian word "учение" -> "учени.." 
results should contain;
učenje/ученје [ut͡ʃɛɲɛ] - n.sg. - learning, teaching

but does only contain "nauka"

**Comment by Translator5** [comment]
Alos one uggestion would be the adding of a proto-slavic word, that is still used in russian today; "грясти" як в "Камо грядеши" – "куда идёшь" – "Камѡ" – куда и "Грѧсти" – идти

https://en.wiktionary.org/wiki/%D0%B3%D1%80%D1%8F%D1%81%D1%82%D0%B8#Russian

**Comment by Translator5** [comment]
слово "жаренная", "сапог" и "бульба" не находится вовсе.

**Comment by ru-danko** [comment]
Dobry denj! 
Prěvod "учение" dlja slova "učenje" dodal jesm.
Čto do pytanja o slovah, ktore se ne nahodet v slovniku, to problem jest v tom, že slovnik ješče ne jest zakončeny, rabota nad dobavjenjem novyh slov i prěvodženjem jestvujučih se prodolžaje.  Prědloziti nove slova vy možete na Fejsbuku v grupě "Medžuslovjansko veče". Ukazati na pogrěšky prěvodov vy možete bezposrednje v našej gugl tabelě, kde se nahodi baza danyh našego slovnika (potrěbujete zaprositi dostup dlja možnosti dovanja komentarov).
Slovo жареный etimologično jest pričestje od glagola жарить - ili na medžuslovjanskom smažiti. Ako pogledite gramatične formy ovogo glagola v aplikaciji, uvidite tam kako izgledajt pričestje - smaženy. T.j. жареный = smaženy. (mimohodom, jest soglasny, že tuto slovo bylo by lepše dodati do slovnika kako pridavnik, ibo ono faktično često koristi se v tutoj kakosti.
Slovo сапог napravdu odsuststvuje.
Dlja slova "тобишь" možno najdti sinonimy, napriměr "to jest", "znači".
Čto jest "бульба", ja ne věm.
"К чему" = "K čemu", "Do čego"

**Comment by Translator5** [comment]
Ѥсть ли изводливость добавјати слова не имаѭћи фейсбука? Просто ꙗ не съглӑсны с йхнојѫ политикоѭ.

**Comment by noomorph** [comment]
@Translator5, можно jест предложити слова в Гугл-табелке: https://docs.google.com/spreadsheets/d/1N79e_yVHDo-d026HljueuKJlAAdeELAiPzdFzdBuKbY (позирај таб на долу, коj се назива "Suggestions").
